begin;

-- 68 new ohio_schools canonical records + 70 ohio_school_aliases rows,
-- verified against the real OHSAA enrollment directory
-- (https://www.ohsaa.org/school-resources/school-enrollment, fetched and
-- parsed directly this session, 815 rows) rather than this project's own
-- incomplete local table. Every OHSAA ID/name/city/district pair below was
-- validated against that real directory and cross-checked for collisions
-- against this project's existing data before this file was written --
-- see dataimports/mock-meet-export/validation-result.json for the full
-- pre-flight check (0 failures on this exact 70+68 set).
--
-- Lakewood (OHSAA 832) and Fairfield (OHSAA 550) are deliberately EXCLUDED
-- from the alias list: this project's ohio_school_aliases table already has
-- a different school aliased under each of those exact names (Lakewood/832
-- vs the existing Lakewood/Hebron/830 alias; Fairfield/550 vs the existing
-- Fairfield/Leesburg/552 alias). Adding a second alias with the same text
-- would not violate the table's own (school_id, normalized_alias) unique
-- constraint, but it would make every future "Lakewood"/"Fairfield" row
-- genuinely ambiguous at match time instead of resolving cleanly -- see
-- the audit note in docs/DECISIONS.md this session for the full reasoning
-- and the proposed permanent fix (source-context-aware disambiguation for
-- every school name multiple real OHSAA schools share).
insert into public.ohio_schools (
  ohsaa_school_id, school_name, normalized_name, city, normalized_city, athletic_district, source_id
) values
  (2100, 'TREE OF LIFE CHRISTIAN', 'tree of life christian', 'Columbus', 'columbus', 'Central', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1166, 'NORTHWEST', 'northwest', 'McDermott', 'mcdermott', 'Southeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1529, 'WELLINGTON SCHOOL', 'wellington school', 'Columbus', 'columbus', 'Central', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (874, 'LIMA CENTRAL CATHOLIC', 'lima central catholic', 'Lima', 'lima', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1234, 'PATRICK HENRY', 'patrick henry', 'Hamler', 'hamler', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1270, 'PORTSMOUTH WEST', 'portsmouth west', 'West Portsmouth', 'west portsmouth', 'Southeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1398, 'SCOTT', 'scott', 'Toledo', 'toledo', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1662, 'WESTERN', 'western', 'Latham', 'latham', 'Southeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (108, 'ALEXANDER', 'alexander', 'Albany', 'albany', 'Southeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1364, 'VILLA ANGELA-ST JOSEPH', 'villa angela st joseph', 'Cleveland', 'cleveland', 'Northeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (782, 'JOHN ADAMS COLLEGE & CAREER ACADEMY', 'john adams college and career academy', 'Cleveland', 'cleveland', 'Northeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (872, 'LIMA SENIOR', 'lima', 'Lima', 'lima', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1598, 'VERMILION', 'vermilion', 'Vermillion', 'vermillion', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (204, 'BERNE UNION', 'berne union', 'Sugar Grove', 'sugar grove', 'Central', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (452, 'DANBURY', 'danbury', 'Lakeside-Marblehead', 'lakeside marblehead', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1238, 'PEEBLES', 'peebles', 'Peebles', 'peebles', 'Southeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (566, 'FAIRPORT HARDING', 'fairport harding', 'Fairport Harbor', 'fairport harbor', 'Northeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (681, 'GROVE CITY CHRISTIAN', 'grove city christian', 'Grove City', 'grove city', 'Central', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (924, 'MADISON SENIOR', 'madison', 'MIddletown', 'middletown', 'Southwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1048, 'MINFORD', 'minford', 'Minford', 'minford', 'Southeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1235, 'PONITZ CAREER TECHNOLOGY CENTER', 'ponitz career technology center', 'Dayton', 'dayton', 'Southwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (220, 'BISHOP READY', 'bishop ready', 'Columbus', 'columbus', 'Central', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1652, 'WELLSTON', 'wellston', 'Wellston', 'wellston', 'Southeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (161, 'BARD HIGH SCHOOL EARLY COLLEGE', 'bard early college', 'Cleveland', 'cleveland', 'Northeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (714, 'HILAND', 'hiland', 'Millersburg', 'millersburg', 'East', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1038, 'MILLER CITY', 'miller city', 'Miller City', 'miller city', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1060, 'MOHAWK', 'mohawk', 'Sycamore', 'sycamore', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1064, 'MONROEVILLE', 'monroeville', 'Monroeville', 'monroeville', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1268, 'PORTSMOUTH', 'portsmouth', 'Portsmouth', 'portsmouth', 'Southeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1414, 'SHAWNEE', 'shawnee', 'Springfield', 'springfield', 'Southwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1506, 'SWANTON', 'swanton', 'Swanton', 'swanton', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1700, 'WHITEHALL-YEARLING', 'whitehall yearling', 'Whitehall', 'whitehall', 'Central', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1120, 'NORTH', 'north', 'Akron', 'akron', 'Northeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1502, 'STRYKER', 'stryker', 'Stryker', 'stryker', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (10037, 'CRISTO REY COLUMBUS', 'cristo rey columbus', 'Columbus', 'columbus', 'Central', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (140, 'LAKESIDE', 'lakeside', 'Ashtabula', 'ashtabula', 'Northeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1184, 'OAK HARBOR', 'oak harbor', 'Oak Harbor', 'oak harbor', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1296, 'RIDGEDALE', 'ridgedale', 'Morral', 'morral', 'Central', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1458, 'SOUTH POINT', 'south point', 'South Point', 'south point', 'Southeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (312, 'CARDINAL STRITCH CATHOLIC', 'cardinal stritch catholic', 'Oregon', 'oregon', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1706, 'WICKLIFFE', 'wickliffe', 'Wickliffe', 'wickliffe', 'Northeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (442, 'CROOKSVILLE', 'crooksville', 'Crooksville', 'crooksville', 'East', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1588, 'VALLEY FORGE', 'valley forge', 'Parma', 'parma', 'Northeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (806, 'KENTON RIDGE', 'kenton ridge', 'Springfield', 'springfield', 'Southwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1468, 'SPENCERVILLE', 'spencerville', 'Spencerville', 'spencerville', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1494, 'STRASBURG-FRANKLIN', 'strasburg franklin', 'Strasburg', 'strasburg', 'East', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1550, 'TROTWOOD-MADISON', 'trotwood madison', 'Trotwood', 'trotwood', 'Southwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (9360, 'COLUMBUS INTERNATIONAL', 'columbus international', 'Columbus', 'columbus', 'Central', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1218, 'OTTOVILLE', 'ottoville', 'Ottoville', 'ottoville', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (294, 'HARRISON CENTRAL', 'harrison central', 'Cadiz', 'cadiz', 'East', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1136, 'NORTHEASTERN', 'northeastern', 'South Vienna', 'south vienna', 'Southwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1176, 'NORWOOD', 'norwood', 'Norwood', 'norwood', 'Southwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1040, 'MILLERSPORT', 'millersport', 'Millersport', 'millersport', 'Central', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1480, 'SPRINGFIELD', 'springfield', 'Springfield', 'springfield', 'Southwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (722, 'HILLTOP', 'hilltop', 'West Unity', 'west unity', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (982, 'MAYSVILLE', 'maysville', 'Zanesville', 'zanesville', 'East', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1290, 'REYNOLDSBURG', 'reynoldsburg', 'Reynoldsburg', 'reynoldsburg', 'Central', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1378, 'ST THOMAS AQUINAS', 'st thomas aquinas', 'Louisville', 'louisville', 'Northeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1310, 'RIVERSIDE', 'riverside', 'DeGraff', 'degraff', 'Southwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (260, 'BROOKLYN', 'brooklyn', 'Brooklyn', 'brooklyn', 'Northeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1750, 'ZANESVILLE', 'zanesville', 'Zanesville', 'zanesville', 'East', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (465, 'DELAWARE CHRISTIAN SCHOOL', 'delaware christian school', 'Delaware', 'delaware', 'Central', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1132, 'NORTH CENTRAL', 'north central', 'Pioneer', 'pioneer', 'Northwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1732, 'WOODWARD', 'woodward', 'Cincinnati', 'cincinnati', 'Southwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1148, 'NORTHRIDGE', 'northridge', 'Dayton', 'dayton', 'Southwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (776, 'JEFFERSON TWP', 'jefferson twp', 'Dayton', 'dayton', 'Southwest', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (384, 'CLEVELAND CENTRAL CATHOLIC', 'cleveland central catholic', 'Cleveland', 'cleveland', 'Northeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026')),
  (1453, 'SOUTH GALLIA', 'south gallia', 'Crown City', 'crown city', 'Southeast', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'))
on conflict (ohsaa_school_id) do nothing;

insert into public.ohio_school_aliases (
  school_id, alias, normalized_alias, source_id, notes
) values
  ((select id from public.ohio_schools where ohsaa_school_id = 1408), 'Shaker Hts.', 'shaker hts', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to SHAKER HEIGHTS (OHSAA 1408).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 710), 'Med Highland', 'med highland', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to HIGHLAND (OHSAA 710).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 822), 'Uniont. Lake', 'uniont lake', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to LAKE (OHSAA 822).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1674), 'Wester. South', 'wester south', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to WESTERVILLE SOUTH (OHSAA 1674).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 704), 'Del. Hayes', 'del hayes', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to DELAWARE HAYES (OHSAA 704).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1154), 'No. Royalton', 'no royalton', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to NORTH ROYALTON (OHSAA 1154).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1366), 'Cle. St. Joseph Acad.', 'cle st joseph acad', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to ST JOSEPH ACADEMY (OHSAA 1366).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 716), 'Hil. Davidson', 'hil davidson', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to HILLIARD DAVIDSON (OHSAA 716).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1348), 'Col. DeSales', 'col desales', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to ST FRANCIS DeSALES (OHSAA 1348).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 602), 'Ft. Loramie', 'ft loramie', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to FORT LORAMIE (OHSAA 602).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1244), 'Mass. Perry', 'mass perry', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to PERRY (OHSAA 1244).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 852), 'Lehman Cath.', 'lehman cath', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to LEHMAN CATHOLIC (OHSAA 852).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 820), 'Mil. Lake', 'mil lake', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to LAKE (OHSAA 820).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 664), 'Grandview Hts.', 'grandview hts', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to GRANDVIEW HEIGHTS (OHSAA 664).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 926), 'Mad. Comprehensive', 'mad comprehensive', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to MADISON COMPREHENSIVE (OHSAA 926).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1168), 'Spr. Northwestern', 'spr northwestern', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to NORTHWESTERN (OHSAA 1168).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1382), 'Tol. St. Ursula Acad.', 'tol st ursula acad', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to ST URSULA ACADEMY (OHSAA 1382).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 198), 'Ben. Logan', 'ben logan', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to BENJAMIN LOGAN (OHSAA 198).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 341), 'Kid. Cent. Christian', 'kid cent christian', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to CENTRAL CHRISTIAN (OHSAA 341).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 998), 'McNicholas', 'mcnicholas', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to ARCHBISHOP McNICHOLAS (OHSAA 998).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 519), 'Rich. Edison', 'rich edison', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to EDISON (OHSAA 519).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 438), 'Con. Crestview', 'con crestview', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to CRESTVIEW (OHSAA 438).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1146), 'No. Olmsted', 'no olmsted', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to NORTH OLMSTED (OHSAA 1146).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 762), 'Jackson', 'jackson', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to JACKSON (OHSAA 762).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 823), 'Lake Center Chr.', 'lake center chr', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to LAKE CENTER CHRISTIAN SCHOOL (OHSAA 823).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 572), 'Sher. Fairview', 'sher fairview', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to FAIRVIEW (OHSAA 572).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 942), 'Mans. Christian', 'mans christian', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to MANSFIELD CHRISTIAN (OHSAA 942).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 824), 'Lake Cath.', 'lake cath', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to LAKE CATHOLIC (OHSAA 824).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1152), 'No. Ridgeville', 'no ridgeville', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to NORTH RIDGEVILLE (OHSAA 1152).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1292), 'Rhodes', 'rhodes', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to RHODES SCHOOL OF ENVIRONMENTAL STUDIES (OHSAA 1292).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1359), 'Ash. St. John', 'ash st john', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to ST JOHN SCHOOL (OHSAA 1359).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1740), 'Wor. Christian', 'wor christian', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to WORTHINGTON CHRISTIAN (OHSAA 1740).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 340), 'Canton C.C.', 'canton c c', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to CANTON CENTRAL CATHOLIC (OHSAA 340).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1624), 'Mass. Washington', 'mass washington', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to WASHINGTON (OHSAA 1624).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 434), 'Ash. Crestview', 'ash crestview', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to CRESTVIEW (OHSAA 434).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 174), 'Beaumont', 'beaumont', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to BEAUMONT SCHOOL (OHSAA 174).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 630), 'Gar. Garfield', 'gar garfield', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to GARFIELD (OHSAA 630).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 700), 'Hathaway Brown', 'hathaway brown', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to HATHAWAY BROWN SCHOOL (OHSAA 700).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 830), 'Heb. Lakewood', 'heb lakewood', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to LAKEWOOD (OHSAA 830).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 868), 'Licking Hts.', 'licking hts', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to LICKING HEIGHTS (OHSAA 868).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1130), 'No. Baltimore', 'no baltimore', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to NORTH BALTIMORE (OHSAA 1130).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1314), 'Cal. River Valley', 'cal river valley', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to RIVER VALLEY (OHSAA 1314).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1180), 'Chardon NDCL', 'chardon ndcl', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to NOTRE DAME-CATHEDRAL LATIN (OHSAA 1180).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 446), 'Cuy. Heights', 'cuy heights', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to CUYAHOGA HEIGHTS (OHSAA 446).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 977), 'Maumee Va. C.D.', 'maumee va c d', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to MAUMEE VALLEY COUNTRY DAY (OHSAA 977).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1450), 'Chil. Southeastern', 'chil southeastern', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to SOUTHEASTERN (OHSAA 1450).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1440), 'Will. South', 'will south', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to SOUTH (OHSAA 1440).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1370), 'Fre. St. Joseph C.C.', 'fre st joseph c c', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to ST JOSEPH CENTRAL CATHOLIC (OHSAA 1370).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1454), 'Rac. Southern', 'rac southern', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to SOUTHERN (OHSAA 1454).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1452), 'S. Char. SE', 's char se', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to SOUTHEASTERN LOCAL (OHSAA 1452).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 9276), 'Calvary Christian', 'calvary christian', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to CALVARY CHRISTIAN SCHOOL (OHSAA 9276).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 610), 'Franklin Hts.', 'franklin hts', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to FRANKLIN HEIGHTS (OHSAA 610).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 492), 'Bea. Eastern', 'bea eastern', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to EASTERN (OHSAA 492).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1466), 'Cin. Spencer Center', 'cin spencer center', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to SPENCER CENTER (OHSAA 1466).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 270), 'Charles F Brush', 'charles f brush', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to BRUSH (OHSAA 270).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1525), 'Andrews Osborne Acad.', 'andrews osborne acad', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to ANDREWS OSBORNE ACADEMY (OHSAA 1525).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1340), 'St. Bernard', 'st bernard', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to ST BERNARD-ELMWOOD PLACE (OHSAA 1340).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1150), 'John. Northridge', 'john northridge', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to NORTHRIDGE (OHSAA 1150).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 368), 'Cin. Co. Day', 'cin co day', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to CINCINNATI COUNTRY DAY (OHSAA 368).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 385), 'Cle. Heights', 'cle heights', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to CLEVELAND HEIGHTS (OHSAA 385).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 9388), 'Pat. Liberty Christian', 'pat liberty christian', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to LIBERTY CHRISTIAN ACADEMY (OHSAA 9388).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 9074), 'Wester. Genoa Christian', 'wester genoa christian', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to GENOA CHRISTIAN ACADEMY (OHSAA 9074).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 553), 'Lan. Fair Chr.', 'lan fair chr', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to FAIRFIELD CHRISTIAN ACADEMY (OHSAA 553).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 938), 'Manchester', 'manchester', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to MANCHESTER (OHSAA 938).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1456), 'Sal. Southern', 'sal southern', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to SOUTHERN LOCAL (OHSAA 1456).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 665), 'Gran. Chr. Acad.', 'gran chr acad', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to GRANVILLE CHRISTIAN ACADEMY (OHSAA 665).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1512), 'Syl. Southview', 'syl southview', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to SYLVANIA SOUTHVIEW (OHSAA 1512).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 1360), 'Tol. St. John''s Jesuit', 'tol st john s jesuit', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to ST JOHN''S JESUIT (OHSAA 1360).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 352), 'Cham. Julienne', 'cham julienne', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to CHAMINADE JULIENNE (OHSAA 352).'),
  ((select id from public.ohio_schools where ohsaa_school_id = 372), 'Oregon Clay', 'oregon clay', (select id from public.ohio_data_sources where source_key = 'ohsaa-school-enrollment-2026'), 'Verified against the real OHSAA enrollment directory this session. Resolves to CLAY (OHSAA 372).')
on conflict (school_id, normalized_alias) do nothing;

commit;
